
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ItemExt } from "lib/_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentProps } from '@/lib/component-props';

export namespace Feature.Mulyankan.Practice.ContentBlock {
    export type ContentBlock = {
        fields?: { 
            /**
            * Represents the Body field (047bc5fe-db4f-4891-b33a-6d6554a63596).
            */
            Body: Field<string>;

            /**
            * Represents the Title field (118bfa92-5dc7-42bd-887d-fd3fabd8abbc).
            */
            Title: Field<string>;
        }

    }
    export type ContentBlockFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.Practice.FeaturedNews {
    export type FeatureNews = {
        fields?: { 
            /**
            * Represents the FeaturedTitle field (841280ff-1919-4295-a447-9e1e0d555298).
            */
            FeaturedTitle: Field<string>;

            /**
            * Represents the News field (4e794834-4091-4638-9a33-8eec4182e2a2).
            */
            News: ItemExt[];
        }

    }
    export type FeaturedNewsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.Practice.Common {
    export type News = {
        fields?: { 
            /**
            * Represents the Body field (a4eb36f9-aa13-4a2e-ac31-9a42c9420372).
            */
            Body: Field<string>;

            /**
            * Represents the Subtitle field (070ae4e3-1911-488b-8623-2258c9dcedb6).
            */
            Subtitle: Field<string>;

            /**
            * Represents the Thumbnail field (e71defbb-0aaa-48c2-9bb9-f580fc248542).
            */
            Thumbnail: ImageField;

            /**
            * Represents the Title field (ca85c2e5-5184-4f2f-9ee6-3730fbce2eb2).
            */
            Title: Field<string>;
        }

    }
}
export namespace Feature.Mulyankan.Practice.Category {
    export type NewsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan {
    export type Test = {
        fields?: {         }

    }
}


