
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ItemExt } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentProps } from '@/lib/component-props';

export namespace Feature.Mulyankan.TaazaKhabar.ContentBlock {
    export type ContentBlock = {
        fields?: { 
            /**
            * Represents the Body field (047bc5fe-db4f-4891-b33a-6d6554a63596).
            */
            Body: Field<string>;

            /**
            * Represents the Title field (118bfa92-5dc7-42bd-887d-fd3fabd8abbc).
            */
            Title: Field<string>;
        }

    }
    export type ContentBlockFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.FeaturedNews {
    export type FeatureNews = {
        fields?: { 
            /**
            * Represents the FeaturedTitle field (841280ff-1919-4295-a447-9e1e0d555298).
            */
            FeaturedTitle: Field<string>;

            /**
            * Represents the News field (4e794834-4091-4638-9a33-8eec4182e2a2).
            */
            News: ItemExt[];
        }

    }
    export type FeaturedNewsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations {
    export type Footer = {
        fields?: { 
            /**
            * Represents the categoryLinks field (c67fdef7-e1ac-4291-af12-aa14e0c6c3af).
            */
            categoryLinks: Field<string>;

            /**
            * Represents the categoryLinksLabel field (337493e6-28ee-418c-994f-1a8d3faf0932).
            */
            categoryLinksLabel: Field<string>;

            /**
            * Represents the quickLinks field (2160b095-a258-418c-b4f4-5573a3452827).
            */
            quickLinks: Field<string>;

            /**
            * Represents the quickLinkslabel field (5550c46e-b6c6-4bb7-8c8f-28b6450afd81).
            */
            quickLinkslabel: Field<string>;
        }

    }
    export type FooterFolder = {
        fields?: {         }

    }
    export type Header = {
        fields?: { 
            /**
            * Represents the logo field (7a6976e4-4c9d-4b59-b301-77eaddb18bd7).
            */
            logo: ImageField;
            logoLink:LinkField;

            /**
            * Represents the navLinks field (c254e0b5-c3bd-493e-92b6-ded1d7ff5e39).
            */
            navLinks: ItemExt[];
        }

    }
    export type HeaderFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations.Common {
    export type Link = {
        fields?: { 
            /**
            * Represents the linkTitle field (c67fa2a8-f721-43f1-802e-f81e0d9ad1e2).
            */
            linkTitle: Field<string>;

            /**
            * Represents the url field (f9c25e3d-6b80-412f-8d34-5a25b23d29a1).
            */
            url: LinkField;
        }

    }
    export type LinksFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Common {
    export type News = {
        fields?: { 
            /**
            * Represents the Body field (a4eb36f9-aa13-4a2e-ac31-9a42c9420372).
            */
            Body: Field<string>;

            /**
            * Represents the Subtitle field (070ae4e3-1911-488b-8623-2258c9dcedb6).
            */
            Subtitle: Field<string>;

            /**
            * Represents the Thumbnail field (e71defbb-0aaa-48c2-9bb9-f580fc248542).
            */
            Thumbnail: ImageField;

            /**
            * Represents the Title field (ca85c2e5-5184-4f2f-9ee6-3730fbce2eb2).
            */
            Title: Field<string>;
        }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Category {
    export type NewsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Common.Promo {
    export type PromoFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations.Common {
    export type SocialLink = {
        fields?: {         }

    }
}


