
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ItemExt } from "lib/_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentProps } from '@/lib/component-props';

export namespace Feature.Mulyankan.TaazaKhabar.ContentBlock {
    export type ContentBlock = {
        fields?: { 
            /**
            * Represents the Body field (047bc5fe-db4f-4891-b33a-6d6554a63596).
            */
            Body: Field<string>;

            /**
            * Represents the Title field (118bfa92-5dc7-42bd-887d-fd3fabd8abbc).
            */
            Title: Field<string>;
        }

    }
    export type ContentBlockFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.FeaturedNews {
    export type FeatureNews = {
        fields?: { 
            /**
            * Represents the FeaturedTitle field (841280ff-1919-4295-a447-9e1e0d555298).
            */
            FeaturedTitle: Field<string>;

            /**
            * Represents the News field (4e794834-4091-4638-9a33-8eec4182e2a2).
            */
            News: ItemExt[];
        }

    }
    export type FeaturedNewsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations {
    export type Footer = {
        fields?: { 
            /**
            * Represents the categoryLinks field (c67fdef7-e1ac-4291-af12-aa14e0c6c3af).
            */
            categoryLinks: ItemExt[];

            /**
            * Represents the categoryLinksLabel field (337493e6-28ee-418c-994f-1a8d3faf0932).
            */
            categoryLinksLabel: Field<string>;

            /**
            * Represents the quickLinks field (2160b095-a258-418c-b4f4-5573a3452827).
            */
            quickLinks: ItemExt[];

            /**
            * Represents the quickLinkslabel field (5550c46e-b6c6-4bb7-8c8f-28b6450afd81).
            */
            quickLinkslabel: Field<string>;
        }

    }
    export type FooterFolder = {
        fields?: {         }

    }
    export type Header = {
        fields?: { 
            /**
            * Represents the logo field (7a6976e4-4c9d-4b59-b301-77eaddb18bd7).
            */
            logo: ImageField;

            /**
            * Represents the navLinks field (c254e0b5-c3bd-493e-92b6-ded1d7ff5e39).
            */
            navLinks: ItemExt[];
        }

    }
    export type HeaderFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations.Common {
    export type LinksFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.PageTypes.NewsDetail {
    export type ListingPage = {
        fields?: { 
            /**
            * Represents the listingTitle field (6c6ec991-cb1c-44e9-bb47-473f43a4a883).
            */
            listingTitle: Field<string>;
        }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations.Common {
    export type NavLink = {
        fields?: { 
            /**
            * Represents the linkTitle field (c67fa2a8-f721-43f1-802e-f81e0d9ad1e2).
            */
            linkTitle: Field<string>;

            /**
            * Represents the linkUrl field (f9c25e3d-6b80-412f-8d34-5a25b23d29a1).
            */
            linkUrl: LinkField;
        }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Common {
    export type News = {
        fields?: { 
            /**
            * Represents the Body field (a4eb36f9-aa13-4a2e-ac31-9a42c9420372).
            */
            Body: Field<string>;

            /**
            * Represents the Subtitle field (070ae4e3-1911-488b-8623-2258c9dcedb6).
            */
            Subtitle: Field<string>;

            /**
            * Represents the Thumbnail field (e71defbb-0aaa-48c2-9bb9-f580fc248542).
            */
            Thumbnail: ImageField;

            /**
            * Represents the Title field (ca85c2e5-5184-4f2f-9ee6-3730fbce2eb2).
            */
            Title: Field<string>;
        }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.PageTypes.NewsDetail {
    export type NewsDetailPage = {
        fields?: { 
            /**
            * Represents the autherName field (147c90ac-e37d-44bd-8750-4a89d95b2813).
            */
            autherName: Field<string>;

            /**
            * Represents the body field (0d7b6360-305a-487a-970e-39c109905eaf).
            */
            body: Field<string>;

            /**
            * Represents the createdAt field (86111eb5-8698-4670-ad5c-9bf1305d2d43).
            */
            createdAt: Field<string>;

            /**
            * Represents the subtitle field (6d205d9e-196d-40f9-bd99-9763016f9f9d).
            */
            subtitle: Field<string>;

            /**
            * Represents the tags field (19c77fca-94f7-42cb-b133-39cc8751ed22).
            */
            tags: ItemExt[];

            /**
            * Represents the title field (b56ab711-a4d7-46d7-afd5-9e4362076d76).
            */
            title: Field<string>;
        }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Category {
    export type NewsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Common.NewsTags {
    export type NewsTagsFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.ContentType.Promo {
    export type Promo = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Promo {
    export type PromoFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Common.Promo {
    export type PromoFolder = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Navigations.Common {
    export type SocialLink = {
        fields?: {         }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Common.NewsTags {
    export type Tag = {
        fields?: { 
            /**
            * Represents the value field (56688464-5209-4f0e-8e35-518c987bae2d).
            */
            value: Field<string>;
        }

    }
}
export namespace Feature.Mulyankan.TaazaKhabar.Video {
    export type Video = {
        fields?: { 
            /**
            * Represents the videoTitle field (a0b972ed-3292-45ac-9603-2208ac41bc10).
            */
            videoTitle: Field<string>;

            /**
            * Represents the videoURL field (b02d9cd1-5cdb-4f25-a107-7d86f86236f7).
            */
            videoURL: LinkField;
        }

    }
}


